### ISSUE TITLE
Deeper JSON property access

### ISSUE THREAD

**Issue by kevinpeno** [jamesmoss/flywheel#16]
Currently one cannot query, order by, etc any property that isn't at the top level of a json doc. While this works fine for simple docs, a way to access deeper properties would be nice.

**Comment by stephenwf** [comment]
Quite new to the code base, just looking around just now, but it seems you can access deeper levels using dot notation:
https://github.com/jamesmoss/flywheel/blob/master/src/JamesMoss/Flywheel/Query.php#L96

Also, if you do need some more flexibility, you can extend that class and make it work as you want it too, then a simple configuration change will sort you out with the new functionality. 

I don't expect this repo will be updated for deep searching, as that can get messy quickly and slow things down.

**Comment by jamesmoss** [comment]
Both querying and ordering by nested properties is now supported using dot notation.
