### ISSUE TITLE
Query result with non consecutive array keys

### ISSUE THREAD

**Issue by josecelano** [jamesmoss/flywheel#21]
When I use a 'where' clause in a query:

````
        $result = $this->repository->query()
            ->where('id', '==', $id)
            ->execute();
````
Result array has no consecutive integer keys because array_filter keeps the original keyfor each array value.

So when I use ````$result->first()```` method an exception is thrown becuase 0 offset does not exist:
````php
    public function first()
    {
        return !empty($this->documents) ? $this->documents[0] : false;
    }
````
The problem is documents[0] does not exist if the filter removes the first element in the array.

I have applied this quick patch to Query class:

````php
    public function execute()
    {
        $documents = $this->repo->findAll();

        // DEBUG
        //var_dump($documents);

        if ($this->where) {
            list($field, $operator, $predicate) = $this->where;
            $documents = array_filter($documents, function ($doc) use ($field, $operator, $predicate) {
                $value = $doc->{$field};

                switch (true) {
                    case ($operator === '==' && $value == $predicate): return true;
                    case ($operator === '===' && $value === $predicate): return true;
                    case ($operator === '>'  && $value >  $predicate): return true;
                    case ($operator === '>=' && $value >= $predicate): return true;
                    case ($operator === '<'  && $value <  $predicate): return true;
                    case ($operator === '>=' && $value >= $predicate): return true;
                }

                return false;
            });

            $reindexKeysDocuments = array();
            foreach($documents as $document) {
                $reindexKeysDocuments[] = $document;
            }
            $documents = $reindexKeysDocuments;
        }
````
but maybe you could use another array function as array_walk()

**Comment by jamesmoss** [comment]
`array_values()` is the function you're after. I'll add this fix soon.

**Comment by josecelano** [comment]
I've just realized it. Thanks @jamesmoss I have changed my composer.json to use dev master. You could add a 0.4.1 version fixing that bug. I have spent a lot of time debugging that error (I ahve not seen your reply in my email inbox and I was preparing a pull request ;-)). And thanks for sharing this library, I think it is very useful.

**Comment by josecelano** [comment]
It is working fine with dev master +1

**Comment by jamesmoss** [comment]
I've just tagged 0.4.1 with this fix in.
