### ISSUE TITLE
Multiple orderBy

### ISSUE THREAD

**Issue by DevDaveo** [jamesmoss/flywheel#28]
I'm running constantly in the situation where I need to order twice. Is there any chance this will be added as feature?

**Comment by jamesmoss** [comment]
You can pass an array of strings to order by into `orderBy`  if you want to sort on multiple fields.  e.g

```
$query->orderBy(['name ASC', 'age DESC'])
```

Is this what you were after? I guess this isn't in the documentation right now, I will add it.

**Comment by DevDaveo** [comment]
That's exactly what I needed! Thanks a lot 👍
